# Generated by Django 3.0.4 on 2021-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210302_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='attendants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='customers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='managers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vendors',
            field=models.BooleanField(default=False),
        ),
    ]
