# Generated by Django 4.1.7 on 2023-08-03 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20210312_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_workplace",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_oisStaff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_oisalumni",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_oisguardian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="default.jpg", max_length=255, upload_to="profile_pics"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="url_custom",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="url_facebook",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="url_instagram",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="url_linkedin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="url_twitter",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="OisStaffProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ois_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OisAlumniProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "year_of_graduation",
                    models.CharField(
                        choices=[
                            (1999, "set of 1999"),
                            (2000, "set of 2000"),
                            (2001, "set of 2001"),
                            (2002, "set of 2002"),
                            (2003, "set of 2003"),
                            (2004, "set of 2004"),
                            (2005, "set of 2005"),
                            (2006, "set of 2006"),
                            (2007, "set of 2007"),
                            (2008, "set of 2008"),
                            (2009, "set of 2009"),
                            (2010, "set of 2010"),
                            (2011, "set of 2011"),
                            (2012, "set of 2012"),
                            (2013, "set of 2013"),
                            (2014, "set of 2014"),
                            (2015, "set of 2015"),
                            (2016, "set of 2016"),
                            (2017, "set of 2017"),
                            (2018, "set of 2018"),
                            (2019, "set of 2019"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ois_alumni_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OisAlumniGuardianProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alumni",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.oisalumniprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ois_alumni_guardian_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
