# Generated by Django 4.1.7 on 2023-08-04 06:14

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_user_address_user_age_user_current_workplace_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="administrator",
        ),
        migrations.RemoveField(
            model_name="user",
            name="attendants",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="managers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="moderator",
        ),
        migrations.RemoveField(
            model_name="user",
            name="vendors",
        ),
    ]
