# Generated by Django 4.1.7 on 2023-08-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_driverprofile_fuelvendorprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodriverprofile",
            name="logistics_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.logisticvendorprofile",
            ),
        ),
        migrations.AddField(
            model_name="vendorstaffprofile",
            name="fuel_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fuelvendorprofile",
            ),
        ),
    ]
